spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      allow-pool-suspension: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  config:
    classpath: logback-${spring.profiles.active}.xml

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/insight?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: springboot
  thymeleaf:
    cache: false

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://146.56.97.84:3306/insight?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: springboot
